### ISSUE TITLE
建议添加文章多级导航导航栏，改善代码块行间距等

### ISSUE THREAD

**Issue by TACGqwq** [MaLuns/hexo-theme-async#1]
1. 添加文章多级导航栏（更有利于主题的完整性，以及更利于从其他 Hexo 主题移植至本主题）
2. 改善代码块行间距（代码块中的行间距过小，且文字略小，对于阅读舒适性有可见性影响）
3. 改善滚动条及鼠标中键交互行为（目前滚动条无法上下拖动交互，鼠标中键无法按住以上下拖动）
4. 网页时而会出现滚动到最底部但内容仍未完整的情况（算是比较恶性的问题，本人使用Edge浏览器，除Mojang官网外（此网站本身有问题），其余未出现过此问题，望尽快修复）
5. 明暗切换响应速度有明显延迟

以上所有建议与问题，均使用 Windows11 Edge 100.0.1185.50 访问 www.imalun.com 测试

**Comment by TACGqwq** [comment]
此主题的 UI 设计在 Hexo 中有一定新意（个人见解），但功能上略有缺失和瑕疵，加油
也祝愿你能获得心仪岗位的offor

**Comment by TACGqwq** [comment]
另外，刚发现你 Github 个人信息的国家名称打错了

**Comment by MaLuns** [comment]
1、2、 4、5 做了适当优化调整，3三方插件有问题，暂时未修复。
