### ISSUE TITLE
移动设备顶部不显示网站名

### ISSUE THREAD

**Issue by kbnq** [MaLuns/hexo-theme-async#10]
![微信图片_20221003214449](https://user-images.githubusercontent.com/22976092/193593073-ec23b58c-5f2c-451e-bf18-40eb03211b81.png)
这里不显示网站名。

另外想问一下怎么修改网站配色，比如联系我按钮。

**Comment by MaLuns** [comment]
如果自定义样式，参考 [文档 自定义样式](https://hexo-theme-async.imalun.com/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F-style)，需要覆盖变量参考[这个里文件](https://github.com/MaLuns/hexo-theme-async/tree/master/package/hexo-theme-async/source/css/_variables)
