### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZhuchaWenjiu** [MaLuns/hexo-theme-async#103]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.1.6

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/MaLuns/hexo-theme-async/assets/44519689/ccbd69d0-69ef-4e4e-8adf-28aa1937bd01)
sidebar:
  typedTextPrefix: I`m
  typedText: ["a normal coder"]
  social:
    - name: Github
      icon: fas fa-cloud
      url: https://github.com
边栏按照此示例设置未出现图标，如 https://dracewang.github.io/，https://grainrain.site/ 都有此问题

### 出现问题网站 | Website

https://grainrain.site/

**Comment by MaLuns** [comment]
文件没加载出来吧 我看是正常的
![图片](https://github.com/MaLuns/hexo-theme-async/assets/31614024/310ab5bc-5948-4150-a2fa-5bd72e24466b)
![图片](https://github.com/MaLuns/hexo-theme-async/assets/31614024/2a99ac9d-60d2-422d-a3c6-ac2ec3c45acf)

**Comment by ZhuchaWenjiu** [comment]
这个主题不支持表格么，使用表格的语法没有渲染结果

**Comment by MaLuns** [comment]
> 这个主题不支持表格么，使用表格的语法没有渲染结果

支持表格的，那些都是 hexo md渲染器处理的，如果有增强无法要看 md 渲染器支不支持
