### ISSUE TITLE
[Bug]: 卡加载动画

### ISSUE THREAD

**Issue by c10ck-p** [MaLuns/hexo-theme-async#105]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

v2.1.6

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

开启pjax后，在进行加载动画时依旧可以点击其他页面，反复点击后就会一直卡加载动画(例如反复点击导航栏的不同页面)，直到刷新整个页面。在大佬你的网站上也会这样

### 出现问题网站 | Website

https://www.imalun.com/

**Comment by c10ck-p** [comment]
[Uploading video.zip…]()

**Comment by c10ck-p** [comment]
![bug](https://github.com/MaLuns/hexo-theme-async/assets/125860744/c950957f-d34d-4458-b22c-25e0408c2913)

**Comment by MaLuns** [comment]
v2.1.7 已修改

**Comment by c10ck-p** [comment]
> v2.1.7 已修改

好的
