### ISSUE TITLE
[Bug]: toc置顶后关闭置顶不会消失

### ISSUE THREAD

**Issue by c10ck-p** [MaLuns/hexo-theme-async#106]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

v2.1.7

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在文章的标题处点开toc后选择置顶，然后再取消并不会让toc消失
![bug1](https://github.com/MaLuns/hexo-theme-async/assets/125860744/6f3239a3-f41c-44c7-8731-31027e8b0944)

### 出现问题网站 | Website

https://www.imalun.com/

**Comment by c10ck-p** [comment]
补充：在右下角toc也是取消置顶后不会消失

**Comment by MaLuns** [comment]
🤔️下个小版本优化下这个
