### ISSUE TITLE
[Bug]: 大佬 为什么我文章中代码块显示异常   不能高亮显示  也不显示是什么类型代码

### ISSUE THREAD

**Issue by ambrosecm** [MaLuns/hexo-theme-async#108]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.1.8

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

文章中代码块显示异常   不能高亮显示  也不显示是什么类型代码
已经按文档要求在_config.async.yml中进行配置
![image](https://github.com/MaLuns/hexo-theme-async/assets/96902760/5fd9412d-4ac3-43b7-9479-51eb097df902)
但是在文章中显示仍然有问题
![image](https://github.com/MaLuns/hexo-theme-async/assets/96902760/12d06b81-cf3c-47fa-bc60-b23e7a33fb30)

### 出现问题网站 | Website

https://ambrosecm.github.io/2023/12/06/hello-world/

**Comment by MaLuns** [comment]
检查下配置对不对，看看你 hexo 代码高亮配置是啥

**Comment by MaLuns** [comment]
如果你 hexo 是 7.0.0 版本, 可以添加下如下配置处理
``` yml
# _config.yml
highlight:
  enable: true
```

**Comment by MaLuns** [comment]
v2.1.9 已添加 hexo 7.0.0 配置变动兼容处理

**Comment by ambrosecm** [comment]
解决了   谢谢大佬
