### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ehanblog** [MaLuns/hexo-theme-async#109]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

^2.1.9

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

每次点击页面的按钮跳转的时候异常的卡，慢。（不管是点击文章还是标题都是非常的慢，一直在转圈圈等待好长时间才可以跳转）

### 出现问题网站 | Website

我是在本地运行的时候

**Comment by ehanblog** [comment]
开启科学上网就不卡了，这是为啥

**Comment by MaLuns** [comment]
三方插件 js 是从 CDN 加载的，可以通过配置切换 CDN 源，参考这里 https://hexo-theme-async.imalun.com/guide/config.html#%E6%8F%92%E4%BB%B6-plugins
