### ISSUE TITLE
[Bug]: 本地可以正常运行，但是上传github会报错

### ISSUE THREAD

**Issue by FeatherWaves666** [MaLuns/hexo-theme-async#114]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

lastest

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/MaLuns/hexo-theme-async/assets/77005595/361e1122-a903-4f68-b63e-55e9e53c8393)
![image](https://github.com/MaLuns/hexo-theme-async/assets/77005595/5b61243f-ebe8-4e2c-9a72-9b77bec6d11c)

### 出现问题网站 | Website

https://github.com/FeatherWaves666/FeatherWaves666.github.io/actions/runs/8081686436/job/22080826012

**Comment by MaLuns** [comment]
你看看你 actions 配置构建流程对不对

**Comment by FeatherWaves666** [comment]
> 你看看你 actions 配置构建流程对不对

actions 配置构建流程这个不太懂，下图为action中报错的地方：
![image](https://github.com/MaLuns/hexo-theme-async/assets/77005595/34521059-3c3b-4afe-8796-cbc4f674dbbd)

**Comment by MaLuns** [comment]
如果你是直接部署放 github.io，可以搜下配置怎么写，这类教程挺多的

**Comment by FeatherWaves666** [comment]
没问题的，解决了，感谢点拨

> 如果你是直接部署放 github.io，可以搜下配置怎么写，这类教程挺多的
