### ISSUE TITLE
[Feature]: Custom 404 text

### ISSUE THREAD

**Issue by DenizKose** [MaLuns/hexo-theme-async#117]
### 想要的功能 | What feature do you want?

Hi!

It'll be awesame to add custom text for 404 page or add possibility to add custom layout through config.

**Comment by MaLuns** [comment]
OK, 404 text configurable will be added to the later version. If you want to customize 404 content, you can not choose the 404 template when customizing the page. At this time, use the page layout without content.

**Comment by DenizKose** [comment]
Thank fo your fast reply!
