### ISSUE TITLE
[Bug]: 缺个空格

### ISSUE THREAD

**Issue by okrc** [MaLuns/hexo-theme-async#127]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

latest

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

<img width="297" alt="image" src="https://github.com/user-attachments/assets/cdf4718d-1611-4ea0-a72e-811bfae80df7">

运行天数那似乎也有空格，但未生效

### 出现问题网站 | Website

https://hexo-theme-async.imalun.com/demosite/

**Comment by okrc** [comment]
https://async-docs.imalun.com/guide/third-party-support.html#%E5%88%86%E6%9E%90%E7%BB%9F%E8%AE%A1
<img width="355" alt="image" src="https://github.com/user-attachments/assets/27e27381-bb5e-43d2-a523-ddd1c1f5347e">
这里似乎多了`个`

**Comment by MaLuns** [comment]
感谢反馈😀🤝🤝
