### ISSUE TITLE
视频问题

### ISSUE THREAD

**Issue by Heluo1** [MaLuns/hexo-theme-async#32]
我想问一下首页视频的外链必须以.MP4结尾吗，我在streamja.com生成了一个视频外链，但是主页面显示不出来。能更改文件让它识别其他外链吗。谢谢

**Comment by MaLuns** [comment]
背景视频 使用的 video 标签，支持格式有限，如果是要支持一下其他格式需要使用三方插件，你可以修改 banner.ejs
