### ISSUE TITLE
“About”页面无法正常显示

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#54]
按使用手册写的config，上周更新之前可用，更新之后关于页一片空白

![image](https://user-images.githubusercontent.com/77619434/212344543-e95ecc58-2850-4cd2-a606-435409f04330.png)

![image](https://user-images.githubusercontent.com/77619434/212344830-f18bb69d-bf73-48f2-8c93-c719cfd0a490.png)

**Comment by MaLuns** [comment]
看了下，是和 hexo-tag-aplayer 冲突了

**Comment by MaLuns** [comment]
你可以在 md 文件里自定义下，不使用配置

**Comment by GrainRainy** [comment]
好的，谢谢您

**Comment by GrainRainy** [comment]
顺便再问一句，为什么这个无法删除呢？
![image](https://user-images.githubusercontent.com/77619434/213687422-9ad5f4ab-8952-42f3-8069-4dab144ea098.png)
