### ISSUE TITLE
height_limit默认为false导致的页面无法正常加载

### ISSUE THREAD

**Issue by TACGqwq** [MaLuns/hexo-theme-async#55]
- 当 height_limit 为 false 或 true 时
![image](https://user-images.githubusercontent.com/71155041/212494330-d53b7d8e-cd81-45b1-829d-982171d67769.png)

只需要改成数值就能会恢复正常，_config.yml 里默认是 false，不注意的话蛮容易看不到的

**Comment by TACGqwq** [comment]
- Hexo v6.3.0
- Async v2.0.0-beta.2

**Comment by MaLuns** [comment]
收到反馈，会在 beta.3 修复

**Comment by MaLuns** [comment]
v2.0.0-beta.3 已发布
