### ISSUE TITLE
图片左对齐导致的页面加载错误

### ISSUE THREAD

**Issue by TACGqwq** [MaLuns/hexo-theme-async#56]
左对齐写法如下：
![0AQIW5L7S)T2($ M8@1451Q](https://user-images.githubusercontent.com/71155041/212540308-5ef5d7c9-40cd-4388-92fc-930f90c0f858.png)

效果如下：
![9QMY2D49{6VO1}RHF2}NTKM](https://user-images.githubusercontent.com/71155041/212540116-3805d6a5-856d-4000-a192-5d27f3893e3f.png)

不知道算不算BUG或者功能缺陷，或者有什么其他的写法可以不出错的，本人不会前端

- Hexo v6.3.0
- Async v2.0.0-beta.2

**Comment by TACGqwq** [comment]
顺便，页面默认显示单栏的情况下，单栏和双栏切换的按钮点击是无效的

**Comment by MaLuns** [comment]
图片对齐是样式 bug，页面配置单栏应该不显示切换按钮，会在 beta.2 修复
