### ISSUE TITLE
大佬，文章封面要怎么加哦？在文章顶部加cover 属性 没用诶

### ISSUE THREAD

**Issue by 2279656909** [MaLuns/hexo-theme-async#6]
---
title: Git命令行
date: 2022-08-31 21:04:44
categories: Git
cover: 'https://picsum.photos/1080/1080?random=123942'      // 这里加了不起作用
---

**Comment by MaLuns** [comment]
cover: 'https://picsum.photos/1080/1080?random=123942' 
换成
photos: [https://picsum.photos/1080/1080?random=123942]

**Comment by 2279656909** [comment]
好的谢谢大佬，另外这个从md内导入之后为什么格式会错乱呀
![image](https://user-images.githubusercontent.com/72898008/187943209-a3e228cb-bb6b-42dc-8ef4-ee7cd59f7cf5.png)

**Comment by MaLuns** [comment]
> 
调试面板看看，是不是有文件没加载出来

**Comment by 2279656909** [comment]
好的谢谢大佬，可以加大佬个联系方式嘛，还是有些问题想请教大佬

**Comment by MaLuns** [comment]
你发我 admin@imalun.com 里，我加你吧😂

**Comment by 2279656909** [comment]
发你邮箱了，大佬

**Comment by MaLuns** [comment]
> 发你邮箱了，大佬

没收到额😂

**Comment by 2279656909** [comment]
我用QQ邮箱发了

**Comment by 2279656909** [comment]
大佬我的QQ：2279656909
![image](https://user-images.githubusercontent.com/72898008/189273777-6d0b9dc1-e542-4c5b-ba14-f84296a14d66.png)

**Comment by MaLuns** [comment]
> 大佬我的QQ：2279656909 ![image](https://user-images.githubusercontent.com/72898008/189273777-6d0b9dc1-e542-4c5b-ba14-f84296a14d66.png)

已加
