### ISSUE TITLE
[Bug]: 带有链接的标题会消失

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#68]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

6.3.0

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

如图，源文件中带链接的标题无法显示

![image](https://user-images.githubusercontent.com/77619434/222937071-6096bab8-fcea-46f3-87bc-0cce16f5a47e.png)

### 出现问题网站 | Website

https://grainrain.netlify.app/2023/03/04/persistable_segment_tree/

**Comment by GrainRainy** [comment]
主题版本2.0.2

**Comment by MaLuns** [comment]
v2.0.3 已修复

**Comment by GrainRainy** [comment]
太高效啦！拜谢作者
