### ISSUE TITLE
[Bug]: 代码块折叠限制行数bug

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#72]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.0.3

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

config 内设置 700 行，实际 50 行左右就会被折叠

![image](https://user-images.githubusercontent.com/77619434/224494786-1cd85a7b-f153-45b0-8e3b-318c8bde9cda.png)

![image](https://user-images.githubusercontent.com/77619434/224494796-45dfb249-e7eb-4d9a-9056-2cd25e3516d2.png)

### 出现问题网站 | Website

https://grainrain.site/2023/01/20/Minimum%20Spanning%20Tree/

**Comment by MaLuns** [comment]
这个高度是代码块高度，不是指的行数，设置 700 就是代码块折叠后最高  700px

**Comment by GrainRainy** [comment]
ok谢谢~
不过一个建议，设置成行数可能更方便调一些
