### ISSUE TITLE
关于评论的配置

### ISSUE THREAD

**Issue by kjhuanhao** [MaLuns/hexo-theme-async#8]
大佬没有搞懂这个评论要怎么配置🥲🥲🥲😭
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-10_19-31-49.png)

**Comment by MaLuns** [comment]
🤣这个其他评论插件都没做适配，只适配了我自己之前写的个

**Comment by MaLuns** [comment]
🤣 你用的哪款评论插件

**Comment by MaLuns** [comment]
非bug 类issue 我先关了，有其他问题 可去 discussions 讨论
