### ISSUE TITLE
[Bug]: 关于在 PC 下 locomotive-scroll.js 接管文章滚动的几个 bug

### ISSUE THREAD

**Issue by ruoxijun** [MaLuns/hexo-theme-async#84]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

"hexo-theme-async": "^2.0.9",

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

1. 滚动文章到的位置与左侧目录所显示位置不一致
2. 点击左侧目录后文章不能滚动至正确位置
3. 左侧目录过长时目录超出屏幕无法查看
4. 浏览器自带 `ctrl+f` 搜索不能跳转至指定位置

* 分辨率：1440*900

### 出现问题网站 | Website

https://ruoxijun.top/post/java/springboot/SpringBoot.html

**Comment by MaLuns** [comment]
最近比较忙没空闲时间折腾这个🤣， 前3个应该还能优化优化解决掉，搜索那个估计只能替换掉 locomotive-scroll.js 插件了😂
