### ISSUE TITLE
[Bug]: 评论产生滚动条时滚动评论页面会同时滚动

### ISSUE THREAD

**Issue by ShawnNotFound** [MaLuns/hexo-theme-async#85]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.0.9

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/MaLuns/hexo-theme-async/assets/97796289/11da560e-c9e2-411c-bb76-8a25fbe1b9c3)
如图，当关闭评论字数限制之后，较长的评论会产生滚动条，但是滚动评论的同时整个页面也会同时滚动

### 出现问题网站 | Website

https://blog.shawn404.top/2023/05/18/pre-share/

**Comment by MaLuns** [comment]
应该是 locomotive-scroll.js 引起后面会替换掉

**Comment by MaLuns** [comment]
2.1.0 已移除 locomotive-scroll
