### ISSUE TITLE
[Bug]: 文章强制单栏后单双栏切换按钮消失

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#87]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.0.9

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在文章内配置单栏后，单双栏切换按钮消失

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/b2e4139b-89bd-425c-b0b5-3c1de1aceadf)

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/ff8e7ace-dff1-4910-ae3d-16d7967c1b61)

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/c2d46210-fd86-4a9a-875d-b4941386ee24)

### 出现问题网站 | Website

grainrain.site

**Comment by MaLuns** [comment]
> 目前是这样设计处理的，设置单栏时生成HTML是不包含侧栏代码的

自定义页面时候可能会需要设置成单栏，不需要切换按钮的
