### ISSUE TITLE
[Bug]: 某些 Latex 内容渲染出错

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#88]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

2.0.9

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

分段函数本地渲染

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/7b47dd47-3fd1-446c-8137-75178084fe55)

页面渲染

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/5f98482f-4e47-4c24-a904-904dbcf55713)

### 出现问题网站 | Website

grainrain.site

**Comment by GrainRainy** [comment]
以及脱式计算, 完全没有渲染

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/4742db75-d16a-45c5-b4d4-58f68af354a8)

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/d067779d-2b1e-403d-ba4a-ef4066ccb3d6)

**Comment by GrainRainy** [comment]
solved. 用 <div> 标签框起来即可, 但这样本地无法正常渲染, 建议写到手册里或者修一下.

**Comment by MaLuns** [comment]
主题里是没对 latex 代码片段做处理得，一般显示异常可能是在 md 里格式有问题
