### ISSUE TITLE
[Bug]: Latex 中含有 '#' 符号会被识别成 html 注释

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#92]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

newest

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

rt, 本地 md 文件中 Latex 16 进制颜色代码的 '#' 被识别成了 html 注释, 整篇文章均被注释. 

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/732cdd6a-d9b2-42b4-ac95-59ff2428a911)

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/89a807a5-e927-431f-9da7-5eacda295b43)

### 出现问题网站 | Website

https://grainrain.site/chtholly_tree/

**Comment by sizdshi** [comment]
我也有此问题

**Comment by MaLuns** [comment]
{# 会被 hexo 解析成 nunjucks 模版，可以在页面配置关闭，

**Comment by MaLuns** [comment]
或者你直接忽略掉 #, 颜色也是能正常渲染的
