### ISSUE TITLE
[Feature]: 关于滚动条滚动后，页面动画有延迟。以及关于TOC的一些建议。

### ISSUE THREAD

**Issue by YesseniaCQ** [MaLuns/hexo-theme-async#97]
### 想要的功能 | What feature do you want?

1. 页面滚动后，滚轮停止了，但页面还在滚，比较晃眼睛，希望大佬能改善下动画。进入阅读模式后稍微好了点，但对我来说比较重要的TOC就没了。
2. 阅读模式进度和正常模式不一样，且从阅读模式回到正常模式后，页面自动返回最上端，希望大佬能够完善到两者同步。
3. TOC如果能够进行简洁舒适的可读性美化，而且保留进阅读模式就好了，万分感谢。
4. 还有主页和归档显示的文章块，可以缩小图片的占比，增加一些文章最上方的简介吗？或者在文章中去除最上面深色的简介段落，加深正文的颜色，而简介保留在文章块或直接从正文去除都行。
![image](https://github.com/MaLuns/hexo-theme-async/assets/116253900/3a9223cc-41aa-47e1-ab94-645d4a8edd64)

**Comment by YesseniaCQ** [comment]
4. 还有主页和归档显示的文章块，可以缩小图片的占比，增加一些文章最上方的简介吗？或者在文章中去除最上面深色的简介段落，加深正文的颜色，而简介保留在文章块或直接从正文去除都行。
![image](https://github.com/MaLuns/hexo-theme-async/assets/116253900/3a9223cc-41aa-47e1-ab94-645d4a8edd64)

**Comment by MaLuns** [comment]
你的版本是多少的，滚动问题 如果2.1以前版本应该 locomotive-scroll 插件引起的，2.1后没复习先这个问题

进入阅读模式 Toc 在2.1以后版本中已经加了，可以看演示站点效果，同步阅读进度的这个暂时没想到好的处理方式，🤣后面看看咋优化

文章卡片这个你可以通过自定义模版去覆盖默认模版，摘要颜色比正文深问题后面会优化下，保持颜色一致😂，当然你也可以先自定义样式覆盖掉主题样式

**Comment by YesseniaCQ** [comment]
版本是2.0.9，然后我更到最新版了，但进入阅读模式后侧栏依旧存在而且跑上面去了（感觉这个帖可以归为bug了🤣
![image](https://github.com/MaLuns/hexo-theme-async/assets/116253900/4db0a692-8f83-49a8-8239-6ceb2ae26a56)
往下滚之后侧栏就贴地了
![image](https://github.com/MaLuns/hexo-theme-async/assets/116253900/0070940a-959c-4114-83ae-cd4073ce818f)
而且上下都有黑块

TOC那个可以提供侧边常驻的选项吗😊真的很需要，如果我是干前端的很想加入大佬一起维护

**Comment by MaLuns** [comment]
> 版本是2.0.9，然后我更到最新版了，但进入阅读模式后侧栏依旧存在而且跑上面去了（感觉这个帖可以归为bug了🤣 ![image](https://user-images.githubusercontent.com/116253900/273587174-4db0a692-8f83-49a8-8239-6ceb2ae26a56.png) 往下滚之后侧栏就贴地了 ![image](https://user-images.githubusercontent.com/116253900/273587287-0070940a-959c-4114-83ae-cd4073ce818f.png) 而且上下都有黑块
> 
> TOC那个可以提供侧边常驻的选项吗😊真的很需要，如果我是干前端的很想加入大佬一起维护
> 
> ———— 二更：刷新几次后黑块消失了，但侧栏bug还在/可怜

有改啥东西吗🤣,我看我的网站和演示站点正常的啊，新版本 TOC 可以文章段落标题 点击图标打开，回头优化增加下固定按钮

**Comment by YesseniaCQ** [comment]
解决了，喜极而泣，感谢大佬耐心解答！
侧栏的bug是因为我自定义的main.ejs最后多了个</html>（其实没自定义什么，就加了个moc3的js），估计复制的时候没仔细看……总之影响了.hidden-sm的效果

话说大佬，自定义模板是不是要把原模版的内容先粘过来，再加自己的内容啊🤔

非计算机专业的孩子试图搞懂……

**Comment by YesseniaCQ** [comment]
还有大佬这个toc的二级目录前面自动加的1.2.之类的，可以把最后的点去掉吗，像我下图这种目录写法就看起来像1.2.2./可怜
![image](https://github.com/MaLuns/hexo-theme-async/assets/116253900/8965e6a3-5f96-4200-85f9-463d0b633593)

**Comment by MaLuns** [comment]
> 解决了，喜极而泣，感谢大佬耐心解答！ 侧栏的bug是因为我自定义的main.ejs最后多了个（其实没自定义什么，就加了个live2d moc3的js），估计复制的时候没仔细看……总之影响了.hidden-sm的效果
> 
> 话说大佬，自定义模板是不是要把原模版的内容先粘过来，再加自己的内容啊🤔
> 
> 非计算机专业的孩子试图搞懂……
> 
> ———— 二更：还没解决…只是在排查的时候把main.ejs从配置里的自定义那块去掉了，改了main.ejs后忘记加回自定义了，我再揣摩揣摩。不过说起来这个bug在2.0.9是木有的
> 
> ————— 三更：我让自定义和main和原来的一样了（整个复制粘贴，没有自己的内容），但侧栏还是bug，大佬可以检查一下是不是设置main的自定义会出问题……期待大佬的答复！
> 
> —————— 四更：我把加的那个moc3的js移入banner.ejs的自定义了，木有问题。所以感觉应该是main设置自定义这件事本身有问题？

🤣toc 那个可以配置不是生成前缀，自定义模版就是替换主题里原来那块内容，🤣你可以直接复制源码过去改，这样可以在不改主题源码情况下，达到自定义效果，也方便后面版本升级

**Comment by MaLuns** [comment]
进入阅读模式 其他元素都是通过 css 隐藏的， 你看看你的，如果代码没报错，看看是不是结构有变动， css 没生效
