### ISSUE TITLE
[Bug]: markdown语法 四级标签后的都会自动添加一个# 号

### ISSUE THREAD

**Issue by sizdshi** [MaLuns/hexo-theme-async#99]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

latest

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![089890f8bdfe7d0f49eb33124d2b8fb](https://github.com/MaLuns/hexo-theme-async/assets/30177132/604391e3-534a-4400-9a8b-a19f9b9f4a6d)

该问题如何解决？已尝试更新hexo-renderer-markdown为[hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it#hexo-renderer-markdown-it)。还是不起作用

### 出现问题网站 | Website

https://www.tctech.asia/2023/09/26/2020-03-25/

**Comment by MaLuns** [comment]
这个是主题里加的, 可以通过添加样式去掉 
``` less
h4:before,
h5:before,
h6:before {
    content: unset;
}
```

**Comment by sizdshi** [comment]
这个具体是在哪个配置文件里添加呀？还是说是在md文件中自己写呢？

**Comment by MaLuns** [comment]
source/_data/style/index.less 

这个文件里

**Comment by sizdshi** [comment]
大佬，试了一下不起作用。
![41e1f42b5cc34cbafea7ad3a2ab0378](https://github.com/MaLuns/hexo-theme-async/assets/30177132/4ed13416-d8a6-4f0b-88c1-8f0b513c2d6a)
![b32f67ffdb31015ed850efeded05ced](https://github.com/MaLuns/hexo-theme-async/assets/30177132/9d390eee-b49e-407a-a3cb-85da5d5fa2c5)

**Comment by MaLuns** [comment]
> 大佬，试了一下不起作用。 ![41e1f42b5cc34cbafea7ad3a2ab0378](https://user-images.githubusercontent.com/30177132/275532999-4ed13416-d8a6-4f0b-88c1-8f0b513c2d6a.png) ![b32f67ffdb31015ed850efeded05ced](https://user-images.githubusercontent.com/30177132/275533013-9d390eee-b49e-407a-a3cb-85da5d5fa2c5.png)

那应该是css 优先级不够你调整下或者直接 !important

**Comment by sizdshi** [comment]
起作用了。（
给不知怎么添加的人：
`
h4:before,
h5:before,
h6:before {
    content: unset !important;
}
`

**Comment by sizdshi** [comment]
起作用了。
给不知道怎么添加的人：
```
h4:before,
h5:before,
h6:before {
    content: unset !important;
}
```
